### ISSUE TITLE
Should compound surnames (like 上官, 司馬, not double surname) keep connected?

### ISSUE THREAD

**Issue by be5invis** [muan/romanize-names#2]
I am not very sure about the rules in Taiwan. In Hong Kong, compound surnames are commonly connected using an hyphen, like this:

> 歐陽桂如法官 Justice AU-YEUNG

**Comment by muan** [comment]
I have seen both, as one word and hyphen connected. I don't think there's a set rule for that. :/ (as is everything else). But I guess the current behavior is definitely wrong (separated with a space).

**Comment by be5invis** [comment]
Maybe maintaining a set of composite surnames is an acceptable solution, but there are double surnames CONTAINING composite surnames, like 王司徒正美...
